# Generated by Django 4.1.9 on 2024-12-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_role_name_vendoritems'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoritems',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
